### ISSUE TITLE
Error: Simple Carousel requires Omeka S ^1.1.0

### ISSUE THREAD

**Issue by rafaeluriarte** [Neo-Inspiration/Omeka-S-SimpleCarousel#2]
I just installed the last version of Omeka (version 2.0.2) but when installing this wonderful plugin I get:
"Error: Simple Carousel requires Omeka S ^1.1.0"

Do you have any plan to update the plugin to the version 2?

Thank you,

**Comment by ray0352** [comment]
Hello, I also need to use this module for a project and am interested in an update for 2.0.

**Comment by NVJobin** [comment]
Any word on this? I just went to install this plug-in and got the same error. It would be amazing if anyone had any information on when/if it will be fixed?

**Comment by ESnark** [comment]
@NVJobin @ray0352 Thanks for your issue. Unfortunately, This module is not under maintenance for now.
I'm not sure when I can update this module but maybe you can modify ini file `/config/module.ini`.

Because I've not tested module compatibility for Omeka S v2.0, Please let me know if this works well and I will update the version constraint.

**Sorry** and Sorry for the late.

```ini
[info]
name         = "Simple Carousel"
description  = "Display carousels into pages"
tags         = ""
license      = "MIT"
author       = "ESnark"
author_link  = "https://github.com/ESnark"
module_link  = "https://github.com/Neo-Inspiration/Omeka-S-SimpleCarousel"
support_link = "https://github.com/Neo-Inspiration/Omeka-S-SimpleCarousel/issues"
configurable = false
version      = "1.2.3"
;modify "^1.1.0" into ">=1.1.0" or "^2.0.0"
;omeka_version_constraint = "^1.1.0"
omeka_version_constraint = ">=1.1.0"
```

**Comment by rafaeluriarte** [comment]
Unfortunately, I have tried it before and does not work. You can add it to the pages, add the attachments but it simply does not appear in the page.

**Comment by ESnark** [comment]
OK, I'm sorry to say that there isn't an updating plan for now.
I irregularly work for Omeka things, that's why I cannot specify the plan.

Thank you for confirmation though. I will update ASAP when there is another chance to work on Omeka.
